version: '3.7'

services:
    db:
      image: mongo:latest
      ports:
         - '27017:27017'

    backend:
      image: backend:latest 
      ports:
        - '3030:3030'
      links:
        - db

    frontend:
      image: ui:latest
      ports:
        - '3000:3000'
